module.exports = [
    "insert"
    , "remove"
    , "rename"
    , "save"
    , "update"
    , "distinct"
    , "drop"
    , "count"
    , "findAndModify"
    , "findAndRemove"
    , "findOne"
    , "createIndex"
    , "ensureIndex"
    , "indexInformation"
    , "dropAllIndexes"
    , "reIndex"
    , "mapReduce"
    , "group"
    , "options"
    , "isCapped"
    , "indexExists"
    , "geoNear"
    , "geoHaystackSearch"
    , "indexes"
    , "aggregate"
    , "stats"
]